# Generated by Django 4.2.7 on 2025-10-04 18:51

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Brief description about the user', max_length=500)),
                ('avatar', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to=accounts.models.avatar_upload_path)),
                ('website', models.URLField(blank=True, help_text="User's personal website")),
                ('location', models.CharField(blank=True, help_text="User's location", max_length=100)),
                ('birth_date', models.DateField(blank=True, help_text="User's birth date", null=True)),
                ('is_email_verified', models.BooleanField(default=False, help_text="Whether user's email is verified")),
                ('email_verification_token', models.CharField(blank=True, help_text='Token for email verification', max_length=100)),
                ('email_verification_sent_at', models.DateTimeField(blank=True, help_text='When the verification email was last sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
                'indexes': [models.Index(fields=['user'], name='profile_user_idx'), models.Index(fields=['is_email_verified'], name='profile_verified_idx'), models.Index(fields=['email_verification_token'], name='profile_token_idx'), models.Index(fields=['-created_at'], name='profile_created_idx')],
            },
        ),
    ]
