# Generated by Django 4.2.7 on 2025-10-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_userrole_role_role_name_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'permissions': [('can_manage_roles', 'Can manage user roles'), ('can_assign_roles', 'Can assign roles to users'), ('can_view_role_management', 'Can view role management interface')]},
        ),
    ]
