# Generated by Django 4.2.7 on 2025-10-05 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_extend_post_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_alter_role_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True, help_text='When the article was saved')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about why the article was saved', max_length=500)),
                ('post', models.ForeignKey(help_text='Post that was saved', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='posts.post')),
                ('user', models.ForeignKey(help_text='User who saved the article', on_delete=django.db.models.deletion.CASCADE, related_name='saved_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_articles',
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['user'], name='saved_articles_user_idx'), models.Index(fields=['post'], name='saved_articles_post_idx'), models.Index(fields=['-saved_at'], name='saved_articles_saved_at_idx'), models.Index(fields=['user', '-saved_at'], name='saved_articles_user_saved_idx')],
                'unique_together': {('user', 'post')},
            },
        ),
    ]
