# Generated by Django 4.2.7 on 2025-10-05 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_savedarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the follow relationship was created')),
                ('follower', models.ForeignKey(help_text='User who is following', on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(help_text='User being followed', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_follows',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['follower'], name='user_follow_follower_idx'), models.Index(fields=['following'], name='user_follow_following_idx'), models.Index(fields=['-created_at'], name='user_follow_created_idx'), models.Index(fields=['follower', '-created_at'], name='user_follow_fol_created_idx'), models.Index(fields=['following', '-created_at'], name='user_follow_ing_created_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
