# Generated by Django 4.2.7 on 2025-10-04 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'permissions': [('can_moderate_posts', 'Can moderate posts'), ('can_schedule_posts', 'Can schedule posts'), ('can_feature_posts', 'Can feature posts'), ('can_view_drafts', 'Can view draft posts'), ('can_publish_posts', 'Can publish posts')]},
        ),
        migrations.AddField(
            model_name='post',
            name='author_user',
            field=models.ForeignKey(blank=True, help_text='User who authored this post', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='scheduled_publish_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the post should be automatically published', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled')], default='draft', help_text='Current status of the post', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this post has been viewed'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author_user'], name='posts_author_user_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author_user', '-created_at'], name='posts_author_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status'], name='posts_status_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['scheduled_publish_date'], name='posts_scheduled_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', '-created_at'], name='posts_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-view_count'], name='posts_view_count_idx'),
        ),
    ]
