# Generated by Django 4.2.7 on 2025-10-05 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_extend_post_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='The uploaded media file', upload_to='media/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], help_text='Type of media file', max_length=20)),
                ('original_name', models.CharField(help_text='Original filename when uploaded', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=255)),
                ('thumbnail', models.ImageField(blank=True, help_text='Generated thumbnail for images', null=True, upload_to='thumbnails/%Y/%m/%d/')),
                ('width', models.PositiveIntegerField(blank=True, help_text='Width of image in pixels', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Height of image in pixels', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this media file', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of media in the post')),
                ('caption', models.TextField(blank=True, help_text='Optional caption for the media')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_file', models.ForeignKey(help_text='Media file attached to the post', on_delete=django.db.models.deletion.CASCADE, related_name='post_attachments', to='posts.mediafile')),
                ('post', models.ForeignKey(help_text='Post this media is attached to', on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='posts.post')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['post', 'order'], name='postmedia_post_order_idx'), models.Index(fields=['media_file'], name='postmedia_media_file_idx')],
                'unique_together': {('post', 'media_file')},
            },
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['-created_at'], name='media_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['uploaded_by'], name='media_uploaded_by_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['file_type'], name='media_file_type_idx'),
        ),
    ]
